FROM apache/airflow:2.10.0

# Switch to root if you need OS libraries here
USER root

# (Optional) Install OS dependencies if any
# RUN apt-get update && apt-get install -y <packages> && rm -rf /var/lib/apt/lists/*

# Switch to airflow user to install Python packages
USER airflow

# Install required providers and dependencies
RUN pip install --no-cache-dir \
    apache-airflow-providers-docker \
    apache-airflow-providers-snowflake \
    apache-airflow-providers-databricks==7.7.1 \
    apache-airflow-providers-slack \
    docker
