-- snowflake/02_raw_tables.sql
-- Raw tables for streaming and batch data ingestion
-- These tables receive data directly from Kafka Connect and batch ETL

USE DATABASE SALES_DW;
USE SCHEMA RAW;
USE WAREHOUSE ETL_WH;

-- Raw sales events table (from Kafka streaming)
CREATE TABLE IF NOT EXISTS SALES_RAW (
    -- Core business fields
    ORDER_ID VARCHAR(50) NOT NULL,
    STORE_ID VARCHAR(50),
    PRODUCT_ID VARCHAR(100),
    PRODUCT_NAME VARCHAR(200),
    CATEGORY VARCHAR(50),
    QUANTITY NUMBER(10,0),
    UNIT_PRICE NUMBER(10,2),
    TOTAL_PRICE NUMBER(12,2),
    SALE_TIMESTAMP TIMESTAMP_NTZ,
    CUSTOMER_ID VARCHAR(50),
    PAYMENT_METHOD VARCHAR(50),
    DISCOUNT NUMBER(5,4),
    STORE_LOCATION VARCHAR(100),

    -- Metadata fields
    INGESTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM VARCHAR(20) DEFAULT 'KAFKA',
    PARTITION_DATE DATE DEFAULT CURRENT_DATE(),

    -- Constraints
    PRIMARY KEY (ORDER_ID, INGESTION_TIMESTAMP)
)
CLUSTER BY (PARTITION_DATE, SALE_TIMESTAMP)
COMMENT = 'Raw sales events from Kafka streaming ingestion';

-- Batch sales data table (from S3/CSV uploads)
CREATE TABLE IF NOT EXISTS SALES_BATCH_RAW (
    -- Core business fields (matching streaming schema)
    ORDER_ID VARCHAR(50) NOT NULL,
    STORE_ID VARCHAR(50),
    PRODUCT_ID VARCHAR(100),
    PRODUCT_NAME VARCHAR(200),
    CATEGORY VARCHAR(50),
    QUANTITY NUMBER(10,0),
    UNIT_PRICE NUMBER(10,2),
    TOTAL_PRICE NUMBER(12,2),
    ORDER_DATE DATE,
    SHIP_DATE DATE,
    SALES NUMBER(12,2),
    PROFIT NUMBER(12,2),

    -- Additional batch-specific fields
    CUSTOMER_SEGMENT VARCHAR(50),
    REGION VARCHAR(50),
    COUNTRY VARCHAR(50),
    STATE VARCHAR(50),
    CITY VARCHAR(100),

    -- Metadata fields
    INGESTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM VARCHAR(20) DEFAULT 'BATCH',
    SOURCE_FILE VARCHAR(200),
    BATCH_ID VARCHAR(50),
    PARTITION_DATE DATE DEFAULT CURRENT_DATE()
)
CLUSTER BY (PARTITION_DATE, ORDER_DATE)
COMMENT = 'Raw sales data from batch CSV file ingestion';

-- Product reference data
CREATE TABLE IF NOT EXISTS PRODUCT_RAW (
    PRODUCT_ID VARCHAR(100) NOT NULL,
    PRODUCT_NAME VARCHAR(200),
    CATEGORY VARCHAR(50),
    SUB_CATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    UNIT_COST NUMBER(10,2),
    UNIT_PRICE NUMBER(10,2),

    -- Metadata
    EFFECTIVE_DATE DATE DEFAULT CURRENT_DATE(),
    INGESTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,

    PRIMARY KEY (PRODUCT_ID, EFFECTIVE_DATE)
)
COMMENT = 'Product master data and attributes';

-- Store reference data
CREATE TABLE IF NOT EXISTS STORE_RAW (
    STORE_ID VARCHAR(50) NOT NULL,
    STORE_NAME VARCHAR(200),
    STORE_LOCATION VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(50),
    COUNTRY VARCHAR(50),
    REGION VARCHAR(50),
    STORE_TYPE VARCHAR(50),
    OPENING_DATE DATE,

    -- Metadata
    EFFECTIVE_DATE DATE DEFAULT CURRENT_DATE(),
    INGESTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,

    PRIMARY KEY (STORE_ID, EFFECTIVE_DATE)
)
COMMENT = 'Store master data and location attributes';

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS IDX_SALES_RAW_TIMESTAMP
    ON SALES_RAW (SALE_TIMESTAMP, CATEGORY);

CREATE INDEX IF NOT EXISTS IDX_SALES_BATCH_DATE
    ON SALES_BATCH_RAW (ORDER_DATE, REGION);

-- Create sequences for surrogate keys
CREATE SEQUENCE IF NOT EXISTS SALES_RAW_SEQ
    START = 1
    INCREMENT = 1
    COMMENT = 'Sequence for sales raw table surrogate keys';

-- Grant permissions for data loading
GRANT INSERT, UPDATE, SELECT ON ALL TABLES IN SCHEMA RAW TO ROLE PUBLIC;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA RAW TO ROLE PUBLIC;

-- Display table creation confirmation
SELECT 'Raw tables created successfully' AS status,
       COUNT(*) AS table_count
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'RAW' AND TABLE_NAME LIKE '%RAW';
