-- snowflake/03_dimensional_tables.sql
-- Star schema dimensional tables for analytics
-- These will be populated by dbt transformations

USE DATABASE SALES_DW;
USE SCHEMA MARTS;
USE WAREHOUSE COMPUTE_WH;

-- Date dimension table
CREATE TABLE IF NOT EXISTS DIM_DATE (
    DATE_KEY NUMBER(8,0) NOT NULL,
    DATE_VALUE DATE NOT NULL,
    DAY_OF_WEEK NUMBER(1,0),
    DAY_OF_MONTH NUMBER(2,0),
    DAY_OF_YEAR NUMBER(3,0),
    DAY_NAME VARCHAR(10),
    WEEK_OF_YEAR NUMBER(2,0),
    WEEK_START_DATE DATE,
    WEEK_END_DATE DATE,
    MONTH_NUMBER NUMBER(2,0),
    MONTH_NAME VARCHAR(10),
    MONTH_ABBREVIATION VARCHAR(3),
    QUARTER NUMBER(1,0),
    QUARTER_NAME VARCHAR(10),
    YEAR_NUMBER NUMBER(4,0),
    IS_WEEKEND BOOLEAN,
    IS_HOLIDAY BOOLEAN,
    HOLIDAY_NAME VARCHAR(50),

    -- Business calendar fields
    FISCAL_YEAR NUMBER(4,0),
    FISCAL_QUARTER NUMBER(1,0),
    FISCAL_MONTH NUMBER(2,0),

    -- Metadata
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    PRIMARY KEY (DATE_KEY)
)
CLUSTER BY (DATE_VALUE, YEAR_NUMBER)
COMMENT = 'Date dimension with calendar and business attributes';

-- Product dimension table
CREATE TABLE IF NOT EXISTS DIM_PRODUCT (
    PRODUCT_KEY NUMBER IDENTITY(1,1),
    PRODUCT_ID VARCHAR(100) NOT NULL,
    PRODUCT_NAME VARCHAR(200),
    CATEGORY VARCHAR(50),
    SUB_CATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    UNIT_COST NUMBER(10,2),
    UNIT_PRICE NUMBER(10,2),
    PROFIT_MARGIN NUMBER(5,4),

    -- Product attributes
    PRODUCT_SIZE VARCHAR(20),
    PRODUCT_COLOR VARCHAR(30),
    PRODUCT_WEIGHT NUMBER(8,2),

    -- Lifecycle fields
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRATION_DATE DATE DEFAULT '2099-12-31',
    IS_CURRENT BOOLEAN DEFAULT TRUE,

    -- Metadata
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    PRIMARY KEY (PRODUCT_KEY),
    UNIQUE (PRODUCT_ID, EFFECTIVE_DATE)
)
CLUSTER BY (CATEGORY, IS_CURRENT)
COMMENT = 'Product dimension with slowly changing attributes';

-- Store dimension table
CREATE TABLE IF NOT EXISTS DIM_STORE (
    STORE_KEY NUMBER IDENTITY(1,1),
    STORE_ID VARCHAR(50) NOT NULL,
    STORE_NAME VARCHAR(200),
    STORE_LOCATION VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(50),
    COUNTRY VARCHAR(50),
    REGION VARCHAR(50),
    STORE_TYPE VARCHAR(50),
    OPENING_DATE DATE,

    -- Geographic attributes
    LATITUDE NUMBER(10,8),
    LONGITUDE NUMBER(11,8),
    TIMEZONE VARCHAR(50),

    -- Store attributes
    STORE_SIZE_SQFT NUMBER(10,0),
    EMPLOYEE_COUNT NUMBER(5,0),

    -- Lifecycle fields
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRATION_DATE DATE DEFAULT '2099-12-31',
    IS_CURRENT BOOLEAN DEFAULT TRUE,

    -- Metadata
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    PRIMARY KEY (STORE_KEY),
    UNIQUE (STORE_ID, EFFECTIVE_DATE)
)
CLUSTER BY (REGION, IS_CURRENT)
COMMENT = 'Store dimension with location and operational attributes';

-- Customer dimension table
CREATE TABLE IF NOT EXISTS DIM_CUSTOMER (
    CUSTOMER_KEY NUMBER IDENTITY(1,1),
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    CUSTOMER_NAME VARCHAR(200),
    CUSTOMER_SEGMENT VARCHAR(50),
    CUSTOMER_TYPE VARCHAR(30),

    -- Demographics
    AGE_RANGE VARCHAR(20),
    GENDER VARCHAR(10),
    INCOME_BRACKET VARCHAR(30),

    -- Geographic info
    CITY VARCHAR(100),
    STATE VARCHAR(50),
    COUNTRY VARCHAR(50),
    REGION VARCHAR(50),

    -- Lifecycle fields
    FIRST_PURCHASE_DATE DATE,
    LAST_PURCHASE_DATE DATE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,

    -- Metadata
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    PRIMARY KEY (CUSTOMER_KEY),
    UNIQUE (CUSTOMER_ID)
)
CLUSTER BY (CUSTOMER_SEGMENT, IS_ACTIVE)
COMMENT = 'Customer dimension with demographic and behavioral attributes';

-- Time dimension for intraday analysis
CREATE TABLE IF NOT EXISTS DIM_TIME (
    TIME_KEY NUMBER(6,0) NOT NULL,
    TIME_VALUE TIME NOT NULL,
    HOUR_24 NUMBER(2,0),
    HOUR_12 NUMBER(2,0),
    AM_PM VARCHAR(2),
    MINUTE_NUMBER NUMBER(2,0),
    SECOND_NUMBER NUMBER(2,0),
    HOUR_MINUTE VARCHAR(5),
    TIME_PERIOD VARCHAR(20),
    BUSINESS_HOUR_FLAG BOOLEAN,

    PRIMARY KEY (TIME_KEY)
)
COMMENT = 'Time dimension for intraday sales analysis';

-- Grant permissions
GRANT SELECT ON ALL TABLES IN SCHEMA MARTS TO ROLE PUBLIC;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA MARTS TO ROLE PUBLIC;

-- Create views for current records only
CREATE OR REPLACE VIEW V_DIM_PRODUCT_CURRENT AS
SELECT * FROM DIM_PRODUCT WHERE IS_CURRENT = TRUE;

CREATE OR REPLACE VIEW V_DIM_STORE_CURRENT AS
SELECT * FROM DIM_STORE WHERE IS_CURRENT = TRUE;

-- Grant view permissions
GRANT SELECT ON ALL VIEWS IN SCHEMA MARTS TO ROLE PUBLIC;

-- Display dimension tables confirmation
SELECT 'Dimensional tables created successfully' AS status,
       COUNT(*) AS table_count
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'MARTS' AND TABLE_NAME LIKE 'DIM_%';
