-- snowflake/04_fact_tables.sql
-- Fact tables for sales analytics and reporting
-- These store the measurable business events

USE DATABASE SALES_DW;
USE SCHEMA MARTS;
USE WAREHOUSE COMPUTE_WH;

-- Main sales fact table
CREATE TABLE IF NOT EXISTS FACT_SALES (
    SALES_KEY NUMBER IDENTITY(1,1),

    -- Foreign keys to dimensions
    DATE_KEY NUMBER(8,0) NOT NULL,
    TIME_KEY NUMBER(6,0),
    PRODUCT_KEY NUMBER NOT NULL,
    STORE_KEY NUMBER NOT NULL,
    CUSTOMER_KEY NUMBER,

    -- Degenerate dimensions (transaction-level details)
    ORDER_ID VARCHAR(50) NOT NULL,
    PAYMENT_METHOD VARCHAR(50),

    -- Additive measures
    QUANTITY_SOLD NUMBER(10,0),
    GROSS_SALES_AMOUNT NUMBER(12,2),
    DISCOUNT_AMOUNT NUMBER(10,2),
    NET_SALES_AMOUNT NUMBER(12,2),
    COST_AMOUNT NUMBER(12,2),
    PROFIT_AMOUNT NUMBER(12,2),

    -- Semi-additive measures
    UNIT_PRICE NUMBER(10,2),
    UNIT_COST NUMBER(10,2),

    -- Non-additive measures (ratios)
    PROFIT_MARGIN_PCT NUMBER(5,4),
    DISCOUNT_PCT NUMBER(5,4),

    -- Transaction context
    SALE_TIMESTAMP TIMESTAMP_NTZ,
    SOURCE_SYSTEM VARCHAR(20),

    -- Metadata
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    -- Constraints
    PRIMARY KEY (SALES_KEY),
    FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY),
    FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM_PRODUCT(PRODUCT_KEY),
    FOREIGN KEY (STORE_KEY) REFERENCES DIM_STORE(STORE_KEY),
    FOREIGN KEY (CUSTOMER_KEY) REFERENCES DIM_CUSTOMER(CUSTOMER_KEY)
)
CLUSTER BY (DATE_KEY, STORE_KEY)
COMMENT = 'Primary sales fact table with transaction-level details';

-- Daily sales summary fact table (pre-aggregated)
CREATE TABLE IF NOT EXISTS FACT_SALES_DAILY (
    DAILY_SALES_KEY NUMBER IDENTITY(1,1),

    -- Dimension keys
    DATE_KEY NUMBER(8,0) NOT NULL,
    PRODUCT_KEY NUMBER NOT NULL,
    STORE_KEY NUMBER NOT NULL,

    -- Aggregated measures
    TRANSACTION_COUNT NUMBER(10,0),
    TOTAL_QUANTITY_SOLD NUMBER(12,0),
    TOTAL_GROSS_SALES NUMBER(15,2),
    TOTAL_DISCOUNT_AMOUNT NUMBER(12,2),
    TOTAL_NET_SALES NUMBER(15,2),
    TOTAL_COST_AMOUNT NUMBER(15,2),
    TOTAL_PROFIT_AMOUNT NUMBER(15,2),

    -- Calculated measures
    AVG_TRANSACTION_SIZE NUMBER(10,2),
    AVG_PROFIT_MARGIN_PCT NUMBER(5,4),
    UNIQUE_CUSTOMERS NUMBER(8,0),

    -- Metadata
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    -- Constraints
    PRIMARY KEY (DAILY_SALES_KEY),
    UNIQUE (DATE_KEY, PRODUCT_KEY, STORE_KEY),
    FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY),
    FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM_PRODUCT(PRODUCT_KEY),
    FOREIGN KEY (STORE_KEY) REFERENCES DIM_STORE(STORE_KEY)
)
CLUSTER BY (DATE_KEY, STORE_KEY)
COMMENT = 'Daily aggregated sales fact table for performance';

-- Inventory fact table (semi-additive)
CREATE TABLE IF NOT EXISTS FACT_INVENTORY (
    INVENTORY_KEY NUMBER IDENTITY(1,1),

    -- Dimension keys
    DATE_KEY NUMBER(8,0) NOT NULL,
    PRODUCT_KEY NUMBER NOT NULL,
    STORE_KEY NUMBER NOT NULL,

    -- Inventory measures (point-in-time)
    BEGINNING_INVENTORY NUMBER(10,0),
    ENDING_INVENTORY NUMBER(10,0),
    UNITS_RECEIVED NUMBER(10,0),
    UNITS_SOLD NUMBER(10,0),
    UNITS_ADJUSTED NUMBER(10,0),

    -- Calculated measures
    DAYS_OF_SUPPLY NUMBER(5,1),
    INVENTORY_TURNOVER NUMBER(8,4),
    STOCKOUT_FLAG BOOLEAN,

    -- Metadata
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    -- Constraints
    PRIMARY KEY (INVENTORY_KEY),
    UNIQUE (DATE_KEY, PRODUCT_KEY, STORE_KEY),
    FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY),
    FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM_PRODUCT(PRODUCT_KEY),
    FOREIGN KEY (STORE_KEY) REFERENCES DIM_STORE(STORE_KEY)
)
CLUSTER BY (DATE_KEY, PRODUCT_KEY)
COMMENT = 'Daily inventory levels and movements by product and store';

-- Customer behavior fact table
CREATE TABLE IF NOT EXISTS FACT_CUSTOMER_BEHAVIOR (
    BEHAVIOR_KEY NUMBER IDENTITY(1,1),

    -- Dimension keys
    DATE_KEY NUMBER(8,0) NOT NULL,
    CUSTOMER_KEY NUMBER NOT NULL,
    STORE_KEY NUMBER NOT NULL,

    -- Behavioral measures
    VISIT_COUNT NUMBER(5,0),
    TRANSACTION_COUNT NUMBER(5,0),
    ITEMS_PURCHASED NUMBER(8,0),
    TOTAL_AMOUNT_SPENT NUMBER(12,2),
    AVERAGE_BASKET_SIZE NUMBER(10,2),

    -- Engagement measures
    TIME_SPENT_MINUTES NUMBER(6,0),
    PAGES_VIEWED NUMBER(8,0),
    CATEGORIES_BROWSED NUMBER(3,0),

    -- Flags
    FIRST_VISIT_FLAG BOOLEAN,
    PURCHASE_FLAG BOOLEAN,
    RETURN_CUSTOMER_FLAG BOOLEAN,

    -- Metadata
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    -- Constraints
    PRIMARY KEY (BEHAVIOR_KEY),
    UNIQUE (DATE_KEY, CUSTOMER_KEY, STORE_KEY),
    FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY),
    FOREIGN KEY (CUSTOMER_KEY) REFERENCES DIM_CUSTOMER(CUSTOMER_KEY),
    FOREIGN KEY (STORE_KEY) REFERENCES DIM_STORE(STORE_KEY)
)
CLUSTER BY (DATE_KEY, CUSTOMER_KEY)
COMMENT = 'Customer behavioral metrics and engagement tracking';

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS IDX_FACT_SALES_DATE_STORE
    ON FACT_SALES (DATE_KEY, STORE_KEY);

CREATE INDEX IF NOT EXISTS IDX_FACT_SALES_PRODUCT_DATE
    ON FACT_SALES (PRODUCT_KEY, DATE_KEY);

-- Grant permissions
GRANT SELECT ON ALL TABLES IN SCHEMA MARTS TO ROLE PUBLIC;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA MARTS TO ROLE PUBLIC;

-- Create useful views for reporting
CREATE OR REPLACE VIEW V_SALES_SUMMARY AS
SELECT
    d.DATE_VALUE,
    p.PRODUCT_NAME,
    p.CATEGORY,
    s.STORE_NAME,
    s.REGION,
    SUM(f.NET_SALES_AMOUNT) AS total_sales,
    SUM(f.PROFIT_AMOUNT) AS total_profit,
    SUM(f.QUANTITY_SOLD) AS total_quantity,
    COUNT(*) AS transaction_count
FROM FACT_SALES f
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
JOIN DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
JOIN DIM_STORE s ON f.STORE_KEY = s.STORE_KEY
GROUP BY d.DATE_VALUE, p.PRODUCT_NAME, p.CATEGORY, s.STORE_NAME, s.REGION;

-- Grant view permissions
GRANT SELECT ON ALL VIEWS IN SCHEMA MARTS TO ROLE PUBLIC;

-- Display fact tables confirmation
SELECT 'Fact tables created successfully' AS status,
       COUNT(*) AS table_count
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'MARTS' AND TABLE_NAME LIKE 'FACT_%';
